# Generated by Django 4.1.2 on 2022-10-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categort',
            new_name='category',
        ),
    ]
