# Generated by Django 4.1.2 on 2022-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_categort_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
