# Generated by Django 4.1.2 on 2022-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priduct_image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
