# Generated by Django 4.1.2 on 2022-10-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product_placement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priduct_image',
            new_name='product_image',
        ),
    ]
