# Generated by Django 4.1.2 on 2022-10-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
