# Generated by Django 4.1.2 on 2022-10-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contactmessage_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='id_url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='placement',
            field=models.CharField(choices=[('recently added', 'recently added'), ('popular', 'popular')], default='recently added', max_length=255),
        ),
    ]
