# Generated by Django 4.1.2 on 2022-10-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_product_slug_alter_product_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
